config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :loans do
    member do
      post :repay
      post :repay_callback
      post :extend
    end
    resources :extensions, shallow: true
  end
  

  root 'loans#index'

end

app/models/extension.rb
class Extension < Finance::Base
	
	validates :days, presence: true, numericality: { only_integer: true, greater_than: 0, less_than: 31 } 
	
	belongs_to :loan
	
	before_create do
		if !loan.blank?
			# set own properties
			self.apr = loan.get_extension_apr
			self.interest = loan.get_extension_cost( self.days )
			self.total = loan.total + self.interest
		end
  end
	
	after_create do
		# update loan
		loan.maturity_date = loan.maturity_date + self.days.days
		loan.total = self.total
		loan.apr = self.apr
		loan.save
	end
	
	def get_total
		return loan.total + loan.get_extension_cost( self.days )
	end
	
	def maturity_date
		return self.loan.maturity_date + self.days.days
	end
	
end

app/models/finance/base.rb
module Finance
  class Base < ActiveRecord::Base
    
    self.abstract_class = true
    
    before_create :generate_uuid
    
    def generate_uuid
      self.uuid = UUIDTools::UUID.random_create.to_s if self.uuid.blank?
    end
    
    def self.primary_key
      return "uuid" if connection.column_exists?( table_name, :uuid )
      super
    end
    
  end
end

app/models/loan.rb
class Loan < Finance::Base
	
	APR = 219.0 # annual percentage rate
	
	validates :user_id, :apr, :principal, :interest, :total, :maturity_date, presence: true
	validates :days, presence: true, numericality: { only_integer: true, greater_than: 0, less_than: 31 } 
	
	belongs_to :user
	accepts_nested_attributes_for :user, :update_only => true
	
	has_many :extensions
	
	# assess riskiness
	before_create do
		self.approved = true
		# reject if user attemts to take out a max loan between 00:00 and 06:00 at night
		if principal == user.max_amount && Time.now.seconds_since_midnight < 6 * 60 * 60
			self.approved = false
			self.decline_reason = 'Max amount in night'
		end
		# reject if too many applications originate from the same IP address
		if Loan.where( :user_ip => self.user_ip, :created_at => (DateTime.now - 1.day)..DateTime.now ).count >= 3
			self.approved = false
			self.decline_reason = 'Too many applications from one IP address'
		end
	end
	
	def days_remaining
		return (maturity_date - Date.today).to_i
	end
	
	def get_extension_apr
		return self.apr * 1.5
	end
	
	def get_extension_cost( no_of_days )
		return principal * get_extension_apr / 365 / 100 * no_of_days
	end
	
	def as_json( options = nil )
		json = super( options )
		json.delete( 'decline_reason' )
		return json
	end
	
end

app/models/user.rb
class User < Finance::Base
  
	validates :name,  presence: true
	validates :phone, presence: true
	validates :iban,  presence: true, uniqueness: true
	
	has_many :loans, lambda{ order( :created_at ) }
	has_one :outstanding_loan, lambda{ where( 'repaid=0' ).where( 'approved=1' ) }, :class_name => 'Loan'
	
	devise :database_authenticatable, :rememberable
	attr_accessor :encrypted_password
	
	def max_amount
		300.0
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :sign_in_user
  
  def sign_in_user
    if current_user.blank?
      user = User.new
      user.save( :validate => false )
      user.remember_me = true
      sign_in( :user, user )
    end
  end

end

app/controllers/extensions_controller.rb
class ExtensionsController < ApplicationController
	
	def new
		@loan = Loan.find(params[:loan_id])
		@extension = loan.extensions.build
	end
	
	def create
		@loan = Loan.find(params[:loan_id])
		@extension = @loan.extensions.build( extension_params )
		respond_to do |format|
      if @extension.save
        format.html { redirect_to root_path, notice: "Loan extended." }
        format.json { render :show, status: :created, location: @extension }
      else
        format.html { render :new }
        format.json { render json: @extension.errors, status: :unprocessable_entity }
      end
    end
	end
	
	private
    # Never trust parameters from the scary internet, only allow the white list through.
    def extension_params
      params.require(:extension).permit( :days )
    end
	
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [:show, :edit, :update, :destroy, :repay, :repay_callback]
  
  # GET /loans
  # GET /loans.json
  def index
    @user = current_user
    
    @loans = @user.loans
    
    @loan = @user.loans.build
    @loan.principal = 300
    @loan.apr = Loan::APR
    @loan.days = 30
    @loan.maturity_date = Date.today + 30.days
    @loan.interest = @loan.principal * @loan.apr / 100 / 365 * 30
    @loan.total = @loan.principal + @loan.interest
    
    if !@user.outstanding_loan.blank?
      @extension = @user.outstanding_loan.extensions.build( :days => 7 )
    end
    
    respond_to do |format|
      format.html
      format.json do
        json = { 'Loan' => @loans }
        render :json => json, :layout => false
      end
    end
    
  end

  # GET /loans/1
  # GET /loans/1.json
  def show
    # update disbursed state if the simulated wait period is over
    # this would not be necessary in a production app
    if @loan.approved && @loan.disburse_after <= DateTime.now
      @loan.update_attribute( :disbursed, true )
    end
  end

  # GET /loans/new
  def new
    user = current_user
    @loan = user.loans.build
  end

  # GET /loans/1/edit
  def edit
  end

  # POST /loans
  # POST /loans.json
  def create
    
    user = current_user
    
    @loan = user.loans.build
    
    @loan.assign_attributes( loan_params )
    
    @loan.apr = Loan::APR
    # should consider also request.env["HTTP_X_FORWARDED_FOR"] and request.env['REMOTE_ADDR'] for better protection
    @loan.user_ip = request.remote_ip
    
    if !@loan.days.blank? && !@loan.principal.blank?
      @loan.maturity_date = Date.today + @loan.days.days
      @loan.interest = @loan.principal * @loan.apr / 365 / 100 * @loan.days
      @loan.total = @loan.principal + @loan.interest
    end
    
    # set timestamp to mark as disbursed at - this is a stub and should not exist in an actual app
    @loan.disburse_after = DateTime.now + ( rand(90) + 30 ).seconds # after 30s to 120s
    
    respond_to do |format|
      if @loan.save
        format.html { redirect_to @loan }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { render :new }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loans/1
  # PATCH/PUT /loans/1.json
  def update
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to @loan, notice: 'Loan was successfully updated.' }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1
  # DELETE /loans/1.json
  def destroy
    #@loan.destroy
    #respond_to do |format|
    #  format.html { redirect_to loans_url, notice: 'Loan was successfully destroyed.' }
    #  format.json { head :no_content }
    #end
  end
  
  # stub to simulate third party payment provider
  def repay
  end
  
  # stub to simulate third party payment provider
  def repay_callback
    respond_to do |format|
      if @loan.update({ repaid: true })
        format.html { redirect_to root_path, notice: 'Loan repaid.' }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan
      @loan = Loan.find(params[:id])
      if @loan.user_id != current_user.uuid
        render :status => :forbidden, :text => "Forbidden fruit"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loan_params
      params.require(:loan).permit( :principal, :days, :submission_date, :submission_timestamp, :extend_by_days, :user_attributes => [ :name, :phone, :iban ] )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/extensions_helper.rb
module ExtensionsHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/extensions/_form.haml
= form_for( [ @extension.loan, @extension ], :html => { :class => "loan_form new_extension", 'data-loan_id' => @extension.loan.uuid } ) do |f|
	.extend
		- if @extension.errors.any?
			#error_explanation
				%h2
					= pluralize(@extension.errors.count, "error")
					&nbsp;prohibited this extension from being saved:
				%ul
					- @extension.errors.full_messages.each do |message|
						%li= message
		.field
			.label_wrap
				= f.label :days, "Extend by:"
				%span.presets
					- [ 7, 14, 30 ].each do |no_of_days|
						%button{ :type => "button", :name => "duration_preset", :value => no_of_days,  :class => "btn-link" } #{no_of_days} days
			.input_wrap
				= f.number_field :days, :class => "form-control primary"
				%span &nbsp;days
				.info
					Loan will need to be repaid by
					.maturity_date= @extension.maturity_date.strftime( "%d.%m.%Y" )
		.repayment
			Total:&nbsp;
			%span.total_wrap
				€
				%span.new_total= number_with_precision(@extension.get_total, precision:2) 
		.calendar
		.actions= f.submit "Extend loan", :class => "btn btn-danger submit"
		.summary
			.line.maturity_date_line
				.name Date of repayment:
				.value_wrap.maturity_date= @extension.maturity_date.strftime( "%d.%m.%Y" )
			.line
				.name Initial loan:
				.value_wrap
					€
					%span.value= number_with_precision(@extension.loan.principal, precision:2)
			.line
				.name Commission accrued so far:
				.value_wrap
					€
					%span.interest= number_with_precision(@extension.loan.interest, precision:2)
			.line
				.name Cost of extension:
				.value_wrap
					€
					%span.extension_cost= number_with_precision(@extension.loan.get_extension_cost( @extension.days ), precision:2)
			.line
				.name New total:
				.value_wrap
					€
					%span.new_total= number_with_precision(@extension.get_total, precision:2)
			

app/views/extensions/new.haml
.row
	.col-sm-6
		.outstanding_loan
			%h2 Outstanding Loan
			= render 'form'

app/views/layouts/application.haml
!!!
%html
	%head
		%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
		%title Assignment
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		= csrf_meta_tags
		%meta{ :name => "viewport", :content => "width=device-width, initial-scale=1" }
		= yield :meta
	%body
		.controller{ 'class' => "container-fluid controller-#{params[:controller]} view-#{params[:action]}", 'data-user_id' => current_user.uuid }
			= yield
			= link_to 'Home', root_path, :class => 'home'

app/views/loans/_current.haml
.outstanding_loan
  %h2 Outstanding Loan
  .time_remaining
    .days= ( loan.maturity_date - Date.today ).to_i
    days until repayment
  
  = form_for( loan, :url => repay_loan_path( loan ), :method => :post, :html => { :class => "loan_form" } ) do |f|
    = f.submit "Pay €#{number_with_precision(loan.total,precision:2)} now", :class => "btn btn-primary submit"
  .or
    .inner or
  = render 'extensions/form'

app/views/loans/_form.haml
.new_loan
  = form_for( @loan, :html => { :class => 'loan_form new_loan_form' } ) do |f|
    %h2 New Loan
    - if @loan.errors.any?
      #error_explanation
        %h2
          = pluralize(@loan.errors.count, "error")
          &nbsp;prohibited this loan from being saved:
        %ul
          - @loan.errors.full_messages.each do |message|
            %li= message
    .field
      .label_wrap
        = f.label :principal, 'How much do you need?'
        %span.presets
          - [ 100, 200, 300 ].each do |principal|
            %button{ :type => "button", :name => "principal_preset", :value => principal, :class => "btn-link" } €#{principal}
      .input_wrap
        = f.number_field :principal, :class => 'form-control primary'
        %span &nbsp;EUR
        .info
          Total amount to repay
          .total
            €
            %span.value= number_with_precision(@loan.total, precision:2)
    .field
      .label_wrap
        = f.label :days, 'For how long?'
        %span.presets
          - [ 7, 14, 30 ].each do |days|
            %button{ :type => "button", :name => "duration_preset", :value => days, :class => "btn-link" } #{days} days
      .input_wrap
        = f.number_field :days, :class => 'form-control primary'
        %span &nbsp;days
        .info
          Date of repayment
          .value.maturity_date= @loan.maturity_date.strftime( "%d.%m.%Y" )
    .repayment
      .calendar
    = f.fields_for :user do |ff|
      = ff.hidden_field :uuid
      .field
        .label_wrap
          = ff.label :name, 'Name'
        .input_wrap
          = ff.text_field :name, :class => 'form-control'
      .field
        .label_wrap
          = ff.label :phone, 'Phone number'
        .input_wrap
          = ff.text_field :phone, :class => 'form-control'
      .field
        .label_wrap
          = ff.label :iban, 'Bank account number (IBAN)'
        .input_wrap
          = ff.text_field :iban, :class => 'form-control'
    .actions
      = f.submit 'Receive money', :class => 'btn btn-primary submit'
    .summary
      .line.maturity_date_line
        .name Date of repayment:
        .value_wrap.maturity_date= @loan.maturity_date.strftime( "%d.%m.%Y" )
      .line
        .name Loan:
        .value_wrap
          €
          %span.principal= number_with_precision(@loan.principal, precision:2)
      .line
        .name Comission:
        .value_wrap
          €
          %span.interest= number_with_precision(@loan.interest, precision:2)
      .line
        .name Total:
        .value_wrap
          %span.total
            €
            %span.value= number_with_precision(@loan.total, precision:2)
      .extension_title Loan Extension
      - [ 7, 14, 30 ].each do |days|
        .line{ 'data-no_of_days' => days }
          .name #{days} days:
          .value_wrap
            €
            %span.value= @loan.get_extension_cost( days )
      
    

app/views/loans/edit.html.haml
%h1 Editing Loan
= render 'form'
= link_to 'Show', @loan
|
= link_to 'Back', loans_path

app/views/loans/index.haml
.row
	- if !notice.blank?
		.notice.bg-success= notice
	.col-sm-6
		- if @user.outstanding_loan.blank?
			= render 'form'
		- else
			= render 'current', :loan => @user.outstanding_loan
	- if @loans.count > 0
		.col-sm-6
			%h2 Loan History
			%table.history.table.table-striped
				%thead
					%tr
						%th Date
						%th Principal
						%th Total
						%th Status
				%tbody
					- @loans.each do |loan|
						- if !loan.new_record?
							%tr{ 'data-id' => loan.uuid }
								%td= loan.created_at.strftime("%d.%m.%Y %H:%M")
								%td €#{number_with_precision(loan.principal, precision:2)}
								%td €#{number_with_precision(loan.total, precision:2)}
								%td.status
									- if loan.disbursed
										- if loan.repaid
											Repaid
										- else
											- if loan.days_remaining < 0
												Past due
											- elsif loan.days_remaining == 0
												Due today
											- elsif loan.days_remaining == 1
												Due tomorrow
											- elsif loan.days_remaining > 1
												Due in #{loan.days_remaining} days
									- else
										- if loan.approved
											Payment in progress
										- else
											Declined
							- if loan.extensions.count > 0
								- loan.extensions.each do |extension|
									%tr.extension
										%td= extension.created_at.strftime("%d.%m.%Y %H:%M")
										%td{ :colspan => 2 } #{extension.days} day extension
										%td +€#{number_with_precision(extension.interest, precision:2)}

app/views/loans/new.haml
.row
	.col-sm-6
		= render 'form'
= link_to 'Back', loans_path

app/views/loans/repay.haml
.notice.bg-info Simulated third party payment step

= form_for( @loan, :url => repay_callback_loan_path( @loan ), :method => :post, :html => { :class => 'loan_form repay_callback' } ) do |f|
  = f.submit 'Yes, I made the payment', :class => 'btn btn-primary submit'

  

app/views/loans/show.haml
- if @loan.approved
	.notice.bg-success Loan approved
	- if @loan.disbursed
		.notice.bg-success Money is in your bank account :)
	-else
		.notice.bg-info Transferring money...
		= content_for :meta do
			%meta{ "http-equiv" => "refresh", "content" => 30 }
- else
	.notice.bg-warning Loan declined :(